### PR TITLE
Improve Android debugging by ignoring SIGSEGV & SIGQUIT signal

### PR DESCRIPTION
**Pull request by qhhonx**
see https://issuetracker.google.com/issues/240007217#comment17

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Thanks for the PR! :)

Curious on a couple of things:
- What happens when there is a genuine SIGSEGV (segmentation fault) in the native code? How is that handled?
- Are both these signals handled the same way in Android Studio? The link mentioned is only for SIGSEGV. If yes it might be safe to do the same here as well.

**Comment by qhhonx** [comment]
I have diff-ed Android Studio `process handle` settings which do only handle SIGSEGV signal, so I copied its setting here.   

For SIGQUIT, which occurs after ANR triggered (see [here](https://www.alibabacloud.com/blog/598232#Monitor%20SIGQUIT%20Signals) or [Google](https://www.google.com/search?q=SIGQUIT+android+art+anr) keywords like "SIGQUIT android art anr" will show more likely docs),  Android Studio did not take care of it,  instead I think it is noisy as SIGSEGV. So, I used it in our private enterprise application. If you have some considerations, I could remove it and keep SIGSEGV only.

**Comment by nisargjhaveri** [comment]
Thanks for the explanation and the references, makes sense. Though, I'd prefer to keep the default configuration as close to Android Studio as possible to avoid surprises. If you don't mind, please update the PR to include only the SIGSEGV part? 

We can always add the one for SIGQUIT in `native.initCommands` for the individual launch config if required for the particular app or setup.

**Comment by qhhonx** [comment]
GOT it. I have used these commands in `native.initCommands` settings that's why this PR comes from.  
BTW, I removed SIGQUIT handle strategy which is inconsistent with Android Studio behaviour.

**Comment by nisargjhaveri** [comment]
Thanks a lot! :)

**Pull request merged**
