### PR TITLE
Add option to configure native signals handler

### PR DESCRIPTION
**Pull request by sr-tream**
I need catch SIGSEGV, when I use attach mode, because libbinder not produce SIGSEGV in attach mode for me, and I can catch errors with memory access

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Is it possible to achieve the same by adding `process handle SIGSEGV ...` to `initCommands`? How would you achieve the same in Android Studio?

**Comment by sr-tream** [comment]
> Is it possible to achieve the same by adding process handle SIGSEGV ... to initCommands

It's work only for clear lldb configurations. With this extension, this option is ignored.

> How would you achieve the same in Android Studio?

I don't use AndroidStudio - it's too bad IDE for native code

**Comment by nisargjhaveri** [comment]
> It's work only for clear lldb configurations. With this extension, this option is ignored.

Adding `process handle SIGBUS SIGSEGV --pass true --stop true --notify true` to `initCommands` is should override the default config. Is that not happening? Do you see anything in the output lm why it might not be working?

I'd prefer to avoid adding specific options unless it's difficult to achieve otherwise or is a very common scenario. I see Android Studio also ignores these signals by default as Android seems to throw these signals a lot more time than when you'd expect.

Also, sorry for the super late reply. This project went under the radar for a while. :/

**Comment by sr-tream** [comment]
> Adding process handle SIGBUS SIGSEGV --pass true --stop true --notify true to initCommands is should override the default config

When I created the PR, I was sure that it didn't work because VSCode didn't know about the `initCommands` field.

Now I tested it, and it's work!

> Also, sorry for the super late reply. This project went under the radar for a while. :/

No big deal, I just rebased the fork because it has other changes like [this](https://github.com/sr-tream/vscode-android-debug/commit/87bafd9c8fe49f7dfdf8b321812ec0368f59e162), but I'm not sure how useful it is, so I didn't create a PR

**Comment by nisargjhaveri** [comment]
#18 attempt to fix the original issue here. See if that helps?

**Comment by sr-tream** [comment]
@nisargjhaveri yes, it's works for me! Tried to add `*(char*)0=0;` and breakpoint triggered inside of ART.

image

**Pull request closed without merging**
